import type { Rule } from "~/types"

export const MAFF_CHICKEN_RULES_PLACEHOLDER: Omit<Rule, "_id">[] = [
  {
    asset_type: "chicken",
    day_offset: 0,
    category: "housing",
    severity: "critical",
    title_kh: "ត្រៀមកន្លែងសម្រាប់កូនមាន់",
    title_en: "Prepare brooder area",
    instructions_kh: "កំដៅ ៣៣°C\nក្រាស់ស្បូវ\nទឹកស្អាត និងចំណីចាប់ផ្តើម",
    instructions_en: "Heat 33°C, dry bedding, clean water + starter feed",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 7,
    category: "vaccine",
    severity: "critical",
    title_kh: "ចាក់វ៉ាក់សាំង Newcastle (ND-IB) ដង​ទី១",
    title_en: "Newcastle + IB vaccine, dose 1",
    instructions_kh: "ប្រើ B1 strain\nដក់ចូលក្នុងភ្នែក ឬច្រមុះ\nធ្វើនៅពេលព្រឹក/ល្ងាច",
    instructions_en: "B1 strain via eye/nose drops, cool hours only",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 14,
    category: "vaccine",
    severity: "critical",
    title_kh: "ចាក់វ៉ាក់សាំង Gumboro ដង​ទី១",
    title_en: "Gumboro vaccine, dose 1",
    instructions_kh: "លាយក្នុងទឹកផឹក\nឲ្យមាន់ឃ្លានបន្តិចមុនផឹក",
    instructions_en: "Mix in drinking water; brief water restriction before",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 21,
    category: "feed",
    severity: "important",
    title_kh: "ផ្លាស់ប្តូរទៅចំណី Grower",
    title_en: "Switch to grower feed",
    instructions_kh: "លាយ ៥០/៥០ ៣ ថ្ងៃ\nបន្ទាប់មកប្តូរពេញ",
    instructions_en: "Mix 50/50 for 3 days, then full switch",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 28,
    category: "vaccine",
    severity: "critical",
    title_kh: "ចាក់វ៉ាក់សាំង Newcastle ដង​ទី២",
    title_en: "Newcastle vaccine, booster",
    instructions_kh: "ដក់ចូលក្នុងភ្នែក ឬច្រមុះ\nគ្រប់ក្បាល",
    instructions_en: "Eye/nose drops; every bird",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 42,
    category: "feed",
    severity: "important",
    title_kh: "ផ្លាស់ប្តូរទៅចំណី Finisher",
    title_en: "Switch to finisher feed",
    instructions_kh: "លាយ ៥០/៥០ ៣ ថ្ងៃ",
    instructions_en: "Transition over 3 days",
    source_page: 0,
  },
  {
    asset_type: "chicken",
    day_offset: 60,
    category: "harvest",
    severity: "info",
    title_kh: "ដល់ពេលចាប់លក់",
    title_en: "Harvest day",
    instructions_kh: "ឈប់ឲ្យចំណី ៦-៨ ម៉ោង មុនចាប់\nទឹកនៅតែឲ្យ",
    instructions_en: "Withhold feed 6–8h before, keep water",
    source_page: 0,
  },
]
